// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rag/rag.proto

package rag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ChatId        string                 `protobuf:"bytes,4,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	TopK          int32                  `protobuf:"varint,5,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,6,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_rag_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_rag_rag_proto_rawDescGZIP(), []int{0}
}

func (x *RetrieveRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RetrieveRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RetrieveRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *RetrieveRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RetrieveRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*ContextChunk        `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	TotalTokens   int32                  `protobuf:"varint,2,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_rag_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_rag_rag_proto_rawDescGZIP(), []int{1}
}

func (x *RetrieveResponse) GetChunks() []*ContextChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *RetrieveResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type ContextChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	SourceUserId  string                 `protobuf:"bytes,3,opt,name=source_user_id,json=sourceUserId,proto3" json:"source_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextChunk) Reset() {
	*x = ContextChunk{}
	mi := &file_rag_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextChunk) ProtoMessage() {}

func (x *ContextChunk) ProtoReflect() protoreflect.Message {
	mi := &file_rag_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextChunk.ProtoReflect.Descriptor instead.
func (*ContextChunk) Descriptor() ([]byte, []int) {
	return file_rag_rag_proto_rawDescGZIP(), []int{2}
}

func (x *ContextChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ContextChunk) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ContextChunk) GetSourceUserId() string {
	if x != nil {
		return x.SourceUserId
	}
	return ""
}

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ChatId        string                 `protobuf:"bytes,5,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_rag_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_rag_rag_proto_rawDescGZIP(), []int{3}
}

func (x *EmbedRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EmbedRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EmbedRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *EmbedRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *EmbedRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *EmbedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EmbedRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *EmbedRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_rag_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_rag_rag_proto_rawDescGZIP(), []int{4}
}

func (x *EmbedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EmbedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rag_rag_proto protoreflect.FileDescriptor

const file_rag_rag_proto_rawDesc = "" +
	"\n" +
	"\rrag/rag.proto\x12\tnexus.rag\"\xb0\x01\n" +
	"\x0fRetrieveRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x12\x17\n" +
	"\achat_id\x18\x04 \x01(\tR\x06chatId\x12\x13\n" +
	"\x05top_k\x18\x05 \x01(\x05R\x04topK\x12!\n" +
	"\fworkspace_id\x18\x06 \x01(\tR\vworkspaceId\"f\n" +
	"\x10RetrieveResponse\x12/\n" +
	"\x06chunks\x18\x01 \x03(\v2\x17.nexus.rag.ContextChunkR\x06chunks\x12!\n" +
	"\ftotal_tokens\x18\x02 \x01(\x05R\vtotalTokens\"d\n" +
	"\fContextChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12$\n" +
	"\x0esource_user_id\x18\x03 \x01(\tR\fsourceUserId\"\xe8\x01\n" +
	"\fEmbedRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\tR\agroupId\x12\x17\n" +
	"\achat_id\x18\x05 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"C\n" +
	"\rEmbedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9c\x01\n" +
	"\n" +
	"RAGService\x12J\n" +
	"\x0fRetrieveContext\x12\x1a.nexus.rag.RetrieveRequest\x1a\x1b.nexus.rag.RetrieveResponse\x12B\n" +
	"\rEmbedAndStore\x12\x17.nexus.rag.EmbedRequest\x1a\x18.nexus.rag.EmbedResponseB/Z-nexus/services/nexus-ai-worker/pkg/pb/rag;ragb\x06proto3"

var (
	file_rag_rag_proto_rawDescOnce sync.Once
	file_rag_rag_proto_rawDescData []byte
)

func file_rag_rag_proto_rawDescGZIP() []byte {
	file_rag_rag_proto_rawDescOnce.Do(func() {
		file_rag_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_rag_proto_rawDesc), len(file_rag_rag_proto_rawDesc)))
	})
	return file_rag_rag_proto_rawDescData
}

var file_rag_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rag_rag_proto_goTypes = []any{
	(*RetrieveRequest)(nil),  // 0: nexus.rag.RetrieveRequest
	(*RetrieveResponse)(nil), // 1: nexus.rag.RetrieveResponse
	(*ContextChunk)(nil),     // 2: nexus.rag.ContextChunk
	(*EmbedRequest)(nil),     // 3: nexus.rag.EmbedRequest
	(*EmbedResponse)(nil),    // 4: nexus.rag.EmbedResponse
}
var file_rag_rag_proto_depIdxs = []int32{
	2, // 0: nexus.rag.RetrieveResponse.chunks:type_name -> nexus.rag.ContextChunk
	0, // 1: nexus.rag.RAGService.RetrieveContext:input_type -> nexus.rag.RetrieveRequest
	3, // 2: nexus.rag.RAGService.EmbedAndStore:input_type -> nexus.rag.EmbedRequest
	1, // 3: nexus.rag.RAGService.RetrieveContext:output_type -> nexus.rag.RetrieveResponse
	4, // 4: nexus.rag.RAGService.EmbedAndStore:output_type -> nexus.rag.EmbedResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rag_rag_proto_init() }
func file_rag_rag_proto_init() {
	if File_rag_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_rag_proto_rawDesc), len(file_rag_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_rag_proto_goTypes,
		DependencyIndexes: file_rag_rag_proto_depIdxs,
		MessageInfos:      file_rag_rag_proto_msgTypes,
	}.Build()
	File_rag_rag_proto = out.File
	file_rag_rag_proto_goTypes = nil
	file_rag_rag_proto_depIdxs = nil
}
