// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: billing/billing.proto

package billing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Tokens        int32                  `protobuf:"varint,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_billing_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{0}
}

func (x *ReportRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ReportRequest) GetTokens() int32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_billing_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{1}
}

func (x *ReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_billing_billing_proto protoreflect.FileDescriptor

const file_billing_billing_proto_rawDesc = "" +
	"\n" +
	"\x15billing/billing.proto\x12\rnexus.billing\"D\n" +
	"\rReportRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06tokens\x18\x02 \x01(\x05R\x06tokens\"*\n" +
	"\x0eReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\\\n" +
	"\x0eBillingService\x12J\n" +
	"\vReportUsage\x12\x1c.nexus.billing.ReportRequest\x1a\x1d.nexus.billing.ReportResponseB7Z5nexus/services/nexus-ai-worker/pkg/pb/billing;billingb\x06proto3"

var (
	file_billing_billing_proto_rawDescOnce sync.Once
	file_billing_billing_proto_rawDescData []byte
)

func file_billing_billing_proto_rawDescGZIP() []byte {
	file_billing_billing_proto_rawDescOnce.Do(func() {
		file_billing_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_billing_proto_rawDesc), len(file_billing_billing_proto_rawDesc)))
	})
	return file_billing_billing_proto_rawDescData
}

var file_billing_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_billing_billing_proto_goTypes = []any{
	(*ReportRequest)(nil),  // 0: nexus.billing.ReportRequest
	(*ReportResponse)(nil), // 1: nexus.billing.ReportResponse
}
var file_billing_billing_proto_depIdxs = []int32{
	0, // 0: nexus.billing.BillingService.ReportUsage:input_type -> nexus.billing.ReportRequest
	1, // 1: nexus.billing.BillingService.ReportUsage:output_type -> nexus.billing.ReportResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_billing_billing_proto_init() }
func file_billing_billing_proto_init() {
	if File_billing_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_billing_proto_rawDesc), len(file_billing_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_billing_proto_goTypes,
		DependencyIndexes: file_billing_billing_proto_depIdxs,
		MessageInfos:      file_billing_billing_proto_msgTypes,
	}.Build()
	File_billing_billing_proto = out.File
	file_billing_billing_proto_goTypes = nil
	file_billing_billing_proto_depIdxs = nil
}
