// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: gateway/gateway.proto

package gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIGatewayService_Generate_FullMethodName       = "/nexus.gateway.AIGatewayService/Generate"
	AIGatewayService_StreamResponse_FullMethodName = "/nexus.gateway.AIGatewayService/StreamResponse"
)

// AIGatewayServiceClient is the client API for AIGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIGatewayServiceClient interface {
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
	StreamResponse(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateChunk], error)
}

type aIGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIGatewayServiceClient(cc grpc.ClientConnInterface) AIGatewayServiceClient {
	return &aIGatewayServiceClient{cc}
}

func (c *aIGatewayServiceClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, AIGatewayService_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIGatewayServiceClient) StreamResponse(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIGatewayService_ServiceDesc.Streams[0], AIGatewayService_StreamResponse_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateRequest, GenerateChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIGatewayService_StreamResponseClient = grpc.ServerStreamingClient[GenerateChunk]

// AIGatewayServiceServer is the server API for AIGatewayService service.
// All implementations must embed UnimplementedAIGatewayServiceServer
// for forward compatibility.
type AIGatewayServiceServer interface {
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
	StreamResponse(*GenerateRequest, grpc.ServerStreamingServer[GenerateChunk]) error
	mustEmbedUnimplementedAIGatewayServiceServer()
}

// UnimplementedAIGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIGatewayServiceServer struct{}

func (UnimplementedAIGatewayServiceServer) Generate(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedAIGatewayServiceServer) StreamResponse(*GenerateRequest, grpc.ServerStreamingServer[GenerateChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamResponse not implemented")
}
func (UnimplementedAIGatewayServiceServer) mustEmbedUnimplementedAIGatewayServiceServer() {}
func (UnimplementedAIGatewayServiceServer) testEmbeddedByValue()                          {}

// UnsafeAIGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIGatewayServiceServer will
// result in compilation errors.
type UnsafeAIGatewayServiceServer interface {
	mustEmbedUnimplementedAIGatewayServiceServer()
}

func RegisterAIGatewayServiceServer(s grpc.ServiceRegistrar, srv AIGatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedAIGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIGatewayService_ServiceDesc, srv)
}

func _AIGatewayService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIGatewayServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIGatewayService_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIGatewayServiceServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIGatewayService_StreamResponse_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIGatewayServiceServer).StreamResponse(m, &grpc.GenericServerStream[GenerateRequest, GenerateChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIGatewayService_StreamResponseServer = grpc.ServerStreamingServer[GenerateChunk]

// AIGatewayService_ServiceDesc is the grpc.ServiceDesc for AIGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.gateway.AIGatewayService",
	HandlerType: (*AIGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _AIGatewayService_Generate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamResponse",
			Handler:       _AIGatewayService_StreamResponse_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gateway/gateway.proto",
}
