// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (tenant_id, workspace_id, group_id, title)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, workspace_id, group_id, title, created_at
`

type CreateChatParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	GroupID     pgtype.UUID `json:"group_id"`
	Title       string      `json:"title"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat,
		arg.TenantID,
		arg.WorkspaceID,
		arg.GroupID,
		arg.Title,
	)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkspaceID,
		&i.GroupID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (tenant_id, workspace_id, name, owner_id, ai_enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, workspace_id, name, owner_id, ai_enabled, created_at
`

type CreateGroupParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	AiEnabled   bool        `json:"ai_enabled"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.TenantID,
		arg.WorkspaceID,
		arg.Name,
		arg.OwnerID,
		arg.AiEnabled,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkspaceID,
		&i.Name,
		&i.OwnerID,
		&i.AiEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getChatByID = `-- name: GetChatByID :one
SELECT id, tenant_id, workspace_id, group_id, title, created_at FROM chats WHERE id = $1
`

func (q *Queries) GetChatByID(ctx context.Context, id pgtype.UUID) (Chat, error) {
	row := q.db.QueryRow(ctx, getChatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkspaceID,
		&i.GroupID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, tenant_id, workspace_id, name, owner_id, ai_enabled, created_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkspaceID,
		&i.Name,
		&i.OwnerID,
		&i.AiEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const listChatsByGroup = `-- name: ListChatsByGroup :many
SELECT id, tenant_id, workspace_id, group_id, title, created_at FROM chats WHERE group_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListChatsByGroup(ctx context.Context, groupID pgtype.UUID) ([]Chat, error) {
	rows, err := q.db.Query(ctx, listChatsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkspaceID,
			&i.GroupID,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByWorkspace = `-- name: ListGroupsByWorkspace :many
SELECT id, tenant_id, workspace_id, name, owner_id, ai_enabled, created_at FROM groups WHERE tenant_id = $1 AND workspace_id = $2
ORDER BY created_at DESC
`

type ListGroupsByWorkspaceParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) ListGroupsByWorkspace(ctx context.Context, arg ListGroupsByWorkspaceParams) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByWorkspace, arg.TenantID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkspaceID,
			&i.Name,
			&i.OwnerID,
			&i.AiEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByChat = `-- name: ListMessagesByChat :many
SELECT id, tenant_id, workspace_id, group_id, chat_id, user_id, role, content, reply_to, reactions, is_deleted, is_edited, created_at, updated_at FROM messages
WHERE chat_id = $1 AND is_deleted = false
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListMessagesByChatParams struct {
	ChatID pgtype.UUID `json:"chat_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListMessagesByChat(ctx context.Context, arg ListMessagesByChatParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByChat, arg.ChatID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkspaceID,
			&i.GroupID,
			&i.ChatID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.ReplyTo,
			&i.Reactions,
			&i.IsDeleted,
			&i.IsEdited,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupAI = `-- name: UpdateGroupAI :exec
UPDATE groups SET ai_enabled = $2 WHERE id = $1
`

type UpdateGroupAIParams struct {
	ID        pgtype.UUID `json:"id"`
	AiEnabled bool        `json:"ai_enabled"`
}

func (q *Queries) UpdateGroupAI(ctx context.Context, arg UpdateGroupAIParams) error {
	_, err := q.db.Exec(ctx, updateGroupAI, arg.ID, arg.AiEnabled)
	return err
}
