// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	GroupID     pgtype.UUID        `json:"group_id"`
	Title       string             `json:"title"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Group struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	Name           string             `json:"name"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	AiEnabled      bool               `json:"ai_enabled"`
	InviteCode     pgtype.Text        `json:"invite_code"`
	Handle         pgtype.Text        `json:"handle"`
	Visibility     string             `json:"visibility"`
	JoinPolicy     string             `json:"join_policy"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	DeletionReason pgtype.Text        `json:"deletion_reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type GroupAuditLog struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	Action    string             `json:"action"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GroupInvite struct {
	Code        string             `json:"code"`
	GroupID     pgtype.UUID        `json:"group_id"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	RoleGranted string             `json:"role_granted"`
	MaxUses     pgtype.Int4        `json:"max_uses"`
	UseCount    int32              `json:"use_count"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	RevokedBy   pgtype.UUID        `json:"revoked_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type GroupMember struct {
	GroupID  pgtype.UUID        `json:"group_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type Message struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	GroupID           pgtype.UUID        `json:"group_id"`
	ChatID            pgtype.UUID        `json:"chat_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Role              string             `json:"role"`
	Content           string             `json:"content"`
	ReplyTo           []byte             `json:"reply_to"`
	Reactions         []byte             `json:"reactions"`
	ThreadCount       int32              `json:"thread_count"`
	ThreadLastReplyAt pgtype.Timestamptz `json:"thread_last_reply_at"`
	IsDeleted         bool               `json:"is_deleted"`
	IsEdited          bool               `json:"is_edited"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type MessageReaction struct {
	ID        pgtype.UUID        `json:"id"`
	MessageID pgtype.UUID        `json:"message_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	UserEmail string             `json:"user_email"`
	Emoji     string             `json:"emoji"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ThreadMessage struct {
	ID              pgtype.UUID        `json:"id"`
	ParentMessageID pgtype.UUID        `json:"parent_message_id"`
	ChatID          pgtype.UUID        `json:"chat_id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	UserEmail       string             `json:"user_email"`
	UserName        pgtype.Text        `json:"user_name"`
	UserAvatar      pgtype.Text        `json:"user_avatar"`
	Content         string             `json:"content"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}


type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Plan      string             `json:"plan"`
	Billing   []byte             `json:"billing"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	AvatarUrl    string             `json:"avatar_url"`
	SystemRole   string             `json:"system_role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastSeen     pgtype.Timestamptz `json:"last_seen"`
}

type Workspace struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}
