// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	GroupID     pgtype.UUID        `json:"group_id"`
	Title       string             `json:"title"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Group struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	AiEnabled   bool               `json:"ai_enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	GroupID     pgtype.UUID        `json:"group_id"`
	ChatID      pgtype.UUID        `json:"chat_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	Content     string             `json:"content"`
	ReplyTo     []byte             `json:"reply_to"`
	Reactions   []byte             `json:"reactions"`
	IsDeleted   bool               `json:"is_deleted"`
	IsEdited    bool               `json:"is_edited"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Plan      string             `json:"plan"`
	Billing   []byte             `json:"billing"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	FirebaseUid string             `json:"firebase_uid"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   string             `json:"avatar_url"`
	SystemRole  string             `json:"system_role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastSeen    pgtype.Timestamptz `json:"last_seen"`
}

type Workspace struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}
