// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error
	CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteGroup(ctx context.Context, id pgtype.UUID) error
	GetChatByID(ctx context.Context, id pgtype.UUID) (Chat, error)
	GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetWorkspaceByID(ctx context.Context, id pgtype.UUID) (Workspace, error)
	GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error)
	GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error)
	ListChatsByGroup(ctx context.Context, groupID pgtype.UUID) ([]Chat, error)
	ListGroupsByWorkspace(ctx context.Context, arg ListGroupsByWorkspaceParams) ([]Group, error)
	ListMessagesByChat(ctx context.Context, arg ListMessagesByChatParams) ([]Message, error)
	ListWorkspaceMembers(ctx context.Context, workspaceID pgtype.UUID) ([]ListWorkspaceMembersRow, error)
	ListWorkspacesByTenant(ctx context.Context, arg ListWorkspacesByTenantParams) ([]Workspace, error)
	RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) error
	UpdateGroupAI(ctx context.Context, arg UpdateGroupAIParams) error
	UpdateLastSeen(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
