// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, firebase_uid, email, display_name, avatar_url, system_role, created_at, last_seen FROM users WHERE firebase_uid = $1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.SystemRole,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, firebase_uid, email, display_name, avatar_url, system_role, created_at, last_seen FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.SystemRole,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (firebase_uid, email, display_name, avatar_url, last_seen)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (firebase_uid) DO UPDATE SET
    email = EXCLUDED.email,
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    last_seen = NOW()
RETURNING id, firebase_uid, email, display_name, avatar_url, system_role, created_at, last_seen
`

type UpsertUserParams struct {
	FirebaseUid string `json:"firebase_uid"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	AvatarUrl   string `json:"avatar_url"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.FirebaseUid,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.SystemRole,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}
