// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	GroupID     pgtype.UUID        `json:"group_id"`
	ChatID      pgtype.UUID        `json:"chat_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	Content     string             `json:"content"`
	ReplyTo     []byte             `json:"reply_to"`
	Reactions   []byte             `json:"reactions"`
	IsDeleted   bool               `json:"is_deleted"`
	IsEdited    bool               `json:"is_edited"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
