// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (
    id,
    tenant_id,
    workspace_id,
    group_id,
    chat_id,
    user_id,
    role,
    content,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW()
)
RETURNING id, tenant_id, workspace_id, group_id, chat_id, user_id, role, content, reply_to, reactions, is_deleted, is_edited, created_at, updated_at
`

type InsertMessageParams struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	GroupID     pgtype.UUID `json:"group_id"`
	ChatID      pgtype.UUID `json:"chat_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Role        string      `json:"role"`
	Content     string      `json:"content"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ID,
		arg.TenantID,
		arg.WorkspaceID,
		arg.GroupID,
		arg.ChatID,
		arg.UserID,
		arg.Role,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkspaceID,
		&i.GroupID,
		&i.ChatID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.ReplyTo,
		&i.Reactions,
		&i.IsDeleted,
		&i.IsEdited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
