// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"
)

type Querier interface {
	InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error)
}

var _ Querier = (*Queries)(nil)
